services:
  arianna:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    working_dir: /app
    command: tail -f /dev/null
